/**
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jonbooz.credentials;

import java.util.ArrayList;
import java.util.List;

/**
 * A library.
 */
public class Library {
    /**
     * A method
     *
     * @return {@code true}
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
